import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { VideoAnalysisResponse } from './video-analysis-response.schema';

@Schema({
  timestamps: true,
  collection: 'video_insights',
})
export class VideoInsight extends Document {
  @Prop({ type: Types.ObjectId, ref: 'Content', index: true, required: true })
  contentId: Types.ObjectId; // Reference to the parent content

  @Prop({ required: true })
  chunkIndex: number;

  @Prop({ required: true })
  startTime: number; // in seconds

  @Prop({ required: true })
  endTime: number; // in seconds

  @Prop({ required: true })
  duration: number; // in seconds

  @Prop({
    required: true,
    enum: ['PENDING', 'GATHERING', 'INSIGHTS_GATHERED', 'FAILED', 'OVERLOADED'],
    default: 'PENDING',
  })
  status: string; // Business-focused status names

  @Prop({ type: String }) // Raw insights extracted from this video segment (markdown format)
  insights?: string; // Unstructured markdown text generated by Gemini

  @Prop()
  modelUsed?: string; // Model used for insight extraction

  @Prop()
  processingTime?: number; // Time taken to gather insights

  @Prop()
  error?: string; // Error message if insight gathering failed

  @Prop({ type: Types.ObjectId, ref: 'Prompt' })
  promptIdUsed?: Types.ObjectId; // Prompt version used for insight gathering

  @Prop()
  promptVersionUsed?: number; // Prompt version used for insight gathering

  @Prop({ type: Date })
  gatheredAt?: Date; // When insights were successfully gathered

  @Prop({ type: Date })
  createdAt: Date;

  @Prop({ type: Date })
  updatedAt: Date;
}

export const VideoInsightSchema = SchemaFactory.createForClass(VideoInsight);

// Index for efficient chunk-level queries
VideoInsightSchema.index({ contentId: 1, chunkIndex: 1 }, { unique: true });
VideoInsightSchema.index({ contentId: 1, status: 1 });